# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2123354c81114dd0ebbdda98b9dbf3fa139182b16439fecc797ffff5506296b842f53fff34c010ab754aad26c30599526b4e72d823e2fd876e92c916683fa0da

test:
  secret_key_base: 91723c16223d29bf462ff972c77cefcbe162ca221f30560a9de1c975488841f1f158ccd0ff29d38f5454260befe2cd5e196554e2e9c055bfdbef8718cb0d4759

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
